#!/bin/bash
#
#SBATCH --partition=medium
#SBATCH --job-name=Download_SRA_Sequences
#SBATCH --error=ErrorOut/Download_SRA_Sequences.err
#SBATCH --output=Output/Download_SRA_Sequences.out
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=16000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=wallenz@uab.edu

module load SRA-Toolkit/2.9.6-1-centos_linux64

./Download_SRA_Sequences.sh

