#!/bin/bash
#
#SBATCH --partition=medium
#SBATCH --job-name=DADA2InferASVs02
#SBATCH --error=../../Script_Output/Dataset2_Output/ErrorOut/DADA2InferASVs02.err
#SBATCH --output=../../Script_Output/Dataset2_Output/Output/DADA2InferASVs02.out
#SBATCH --ntasks=1
#SBATCH --time=36:00:00
#SBATCH --mem-per-cpu=32000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=wallenz@uab.edu

#Load a module of R to get the correct environment for running R, then unload the module to be able to use manually installed R
module load R/3.5.0-intel-2017a-X11-20170314-bare
module unload R 

Rscript 3.DADA2InferASVs02.R

