#!/bin/bash
#
#SBATCH --partition=medium
#SBATCH --job-name=SparCC_Corr_Matrix_CreateGephiTables
#SBATCH --error=../Script_Output/Dataset1_Output/ErrorOut/SparCC_Corr_Matrix_CreateGephiTables.err
#SBATCH --output=../Script_Output/Dataset1_Output/Output/SparCC_Corr_Matrix_CreateGephiTables.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem-per-cpu=16000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=wallenz@uab.edu

#Load a module of R to get the correct environment for running R, then unload the module to be able to use manually installed R
module load R/3.5.0-intel-2017a-X11-20170314-bare
module unload R

Rscript 9.SparCC_Corr_Matrix_CreateGephiTables.R

