#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=Dataset1_vs_Dataset2_L6
#SBATCH --error=../Script_Output/Joint_Analyses_Output/ErrorOut/Dataset1_vs_Dataset2_Genus_Rel_Abun.err
#SBATCH --output=../Script_Output/Joint_Analyses_Output/Output/Dataset1_vs_Dataset2_Genus_Rel_Abun.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem-per-cpu=16000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=wallenz@uab.edu

module load R/3.5.0-intel-2017a-X11-20170314-bare  
module unload R

Rscript Dataset1_vs_Dataset2_Genus_Rel_Abun.R

