#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=NCBI_BLAST_PDsigTaxaASVs
#SBATCH --error=../Script_Output/Joint_Analyses_Output/ErrorOut/NCBI_BLAST_PDsigTaxaASVs.err
#SBATCH --output=../Script_Output/Joint_Analyses_Output/Output/NCBI_BLAST_PDsigTaxaASVs.out
#SBATCH --ntasks=1
#SBATCH --time=5:00:00
#SBATCH --mem-per-cpu=32000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=wallenz@uab.edu

#Load a module of R to get the correct environment for running R, then unload the module to be able to use manually installed R
module load R/3.5.0-intel-2017a-X11-20170314-bare
module unload R

#Set path of ncbi bin/ directory
PATH=$PATH:../Support_Files/ncbi-blast-2.9.0+/bin

Rscript NCBI_BLAST_PDsigTaxaASVs.R

