#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=RemovePrimer
#SBATCH --error=../../Script_Output/Dataset1_Output/ErrorOut/RemovePrimer.err
#SBATCH --output=../../Script_Output/Dataset1_Output/Output/RemovePrimer.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem-per-cpu=8000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=wallenz@uab.edu

#cutadapt was downloaded in a conda base environment, so load that environment to use cutadapt
#Enable the 'conda' command
. /home/wallenz/miniconda3/etc/profile.d/conda.sh

#Load conda base environment
conda activate base

./1.RemovePrimer.sh

